---
prod_servers:
  vars:
    admin_user: linuxuser
    util_user: transcribro # non privileged, can only update website files
    server_addr: 107.191.55.250

  hosts:
    prod_server_admin:
      ansible_host: "{{ server_addr }}"
      ansible_user: "{{ admin_user }}"
      ansible_ssh_private_key_file: "keys/admin_user"
      
    prod_server_util:
      ansible_host: "{{ server_addr }}"
      ansible_user: "{{ util_user }}"
      ansible_ssh_private_key_file: "keys/util_user"
