name: fastapi-github-actions-test

on:
  push:
    branches: [main]
    paths:
      - "server/**"
  pull_request:
    branches: [main]
    paths:
      - "server/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg wkhtmltopdf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server

      - name: Lint with Black
        run: black --check .
        working-directory: server

      - name: Run PyTest with coverage
        run: coverage run -m pytest
        working-directory: server

      - name: Print coverage report
        run: coverage report
        working-directory: server

  release-container:
    needs: build-and-test
    uses: ./.github/workflows/server-container.yml
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      container-registry: ghcr.io
      registry-username: ${{ github.repository_owner }}
      working-directory: ./server
