name: test-server-code
on:
  push:
    branches: [main]
    paths:
      - "server/**"
  pull_request:
    branches: [main]
    paths:
      - "server/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/server-test.yml
