name: fastapi-github-actions-test

on:
  push:
    branches: [main]
    paths:
      - "server/**"
  pull_request:
    branches: [main]
    paths:
      - "server/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: sudo apt-get install -y ffmpeg wkhtmltopdf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server

      - name: Lint with Black
        run: black --check .
        working-directory: server

      - name: Run PyTest with coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: coverage run -m pytest
        working-directory: server

      - name: Print coverage report
        run: coverage report
        working-directory: server

    # Add additional jobs for deployment if needed
